// Snapshot tipado de los 30 TC-CHIP, copiado de
// TQD-1128/.qa_reformulacion/cases.json (Revision 2, 08/09/2026).
// Este repo es autocontenido: NO referencia esa ruta externa en runtime.
// Si cases.json cambia, este archivo se debe resincronizar a mano.

export type ChipModule =
  | 'Configuración'
  | 'Condiciones y datos'
  | 'Filtrado'
  | 'Diseño'
  | 'Opciones'
  | 'Integración y dispositivos'
  | 'Regresión';

export interface ChipCase {
  id: number;
  code: string;
  title: string;
  module: ChipModule;
  priority: 'ALTA' | 'MEDIA';
  objective: string;
  source: string;
}

export const chipCases: ChipCase[] = [
  {
    id: 1,
    code: 'TC-CHIP-01',
    title: 'Guardado y persistencia de un chip existente',
    module: 'Configuración',
    priority: 'ALTA',
    objective: 'Comprobar que un cambio identificable en el texto normal de un chip persiste después de APLICAR, GUARDAR y recargar el Site Editor.',
    source: 'UH, criterio de configuración sin deploy; guía 3.6.',
  },
  {
    id: 2,
    code: 'TC-CHIP-02',
    title: 'Visualización de un cambio guardado sin deploy',
    module: 'Configuración',
    priority: 'ALTA',
    objective: 'Verificar que el texto persistido en Site Editor se muestre en la tienda del mismo ambiente sin desplegar código.',
    source: 'UH, chips sin deploy; guía 3.1 y 3.6.',
  },
  {
    id: 3,
    code: 'TC-CHIP-03',
    title: 'Creación de un chip simple',
    module: 'Configuración',
    priority: 'ALTA',
    objective: 'Validar el alta de un chip con condición VTEX y contenido visual explícito.',
    source: 'UH, creación de chips; guía 3.3 y 6.4.',
  },
  {
    id: 4,
    code: 'TC-CHIP-04',
    title: 'Orden de presentación de los chips',
    module: 'Configuración',
    priority: 'MEDIA',
    objective: 'Comprobar que la barra respeta el orden de la lista configurada para los chips aplicables.',
    source: 'Guía 3.6.',
  },
  {
    id: 5,
    code: 'TC-CHIP-05',
    title: 'Condición booleana desde MasterData',
    module: 'Condiciones y datos',
    priority: 'ALTA',
    objective: 'Verificar que un chip evalúe un atributo booleano real de la sucursal desde MasterData.',
    source: 'Guía 6.1, 6.2 y 6.4.',
  },
  {
    id: 6,
    code: 'TC-CHIP-06',
    title: 'Comparaciones de igualdad y contenido',
    module: 'Condiciones y datos',
    priority: 'ALTA',
    objective: 'Verificar los operadores es igual a, es distinto de y contiene con valores existentes y resultados conocidos.',
    source: 'Guía 6.3.',
  },
  {
    id: 7,
    code: 'TC-CHIP-07',
    title: 'Condición VTEX según el contexto del carrito',
    module: 'Condiciones y datos',
    priority: 'ALTA',
    objective: 'Comprobar que Retiro/envío sin costo se evalúe con los datos logísticos del carrito y ubicación actuales.',
    source: 'Guía 6.1 y 6.2; hipótesis de diagnóstico del contexto Copilot.',
  },
  {
    id: 8,
    code: 'TC-CHIP-08',
    title: 'Disponibilidad del chip según la búsqueda',
    module: 'Filtrado',
    priority: 'ALTA',
    objective: 'Validar que un chip activo sólo se ofrezca si la búsqueda base tiene al menos una sucursal coincidente.',
    source: 'Guía 3.1 y preguntas frecuentes.',
  },
  {
    id: 9,
    code: 'TC-CHIP-09',
    title: 'Selección y limpieza de un filtro simple',
    module: 'Filtrado',
    priority: 'ALTA',
    objective: 'Validar que un chip reduzca el listado a sus coincidencias y que quitarlo recupere la búsqueda base.',
    source: 'Guía 3.1.',
  },
  {
    id: 10,
    code: 'TC-CHIP-10',
    title: 'Combinación de dos filtros con coincidencias',
    module: 'Filtrado',
    priority: 'ALTA',
    objective: 'Comprobar la lógica AND entre dos chips y la permanencia del filtro restante al quitar uno.',
    source: 'Guía 3.1, combinación de condiciones.',
  },
  {
    id: 11,
    code: 'TC-CHIP-11',
    title: 'Cambio de ubicación con filtros activos',
    module: 'Regresión',
    priority: 'ALTA',
    objective: 'Revalidar el problema reportado de listado vacío al cambiar de ubicación con chips seleccionados.',
    source: 'FARMA-5049, Actividad D5; TQD-1128, Actividad D4; guía 3.1.',
  },
  {
    id: 12,
    code: 'TC-CHIP-12',
    title: 'Estados visuales normal y seleccionado',
    module: 'Diseño',
    priority: 'MEDIA',
    objective: 'Verificar que un chip simple use el diseño configurado para normal y seleccionado.',
    source: 'UH, tres estados de chip; guía 3.2.',
  },
  {
    id: 13,
    code: 'TC-CHIP-13',
    title: 'Visibilidad del chip dentro de la tarjeta',
    module: 'Diseño',
    priority: 'MEDIA',
    objective: 'Validar los tres modos de presentación de un chip simple dentro de las tarjetas de sucursal.',
    source: 'Guía 3.2 y 3.4.',
  },
  {
    id: 14,
    code: 'TC-CHIP-14',
    title: 'Contenido y orden de los elementos del chip',
    module: 'Diseño',
    priority: 'MEDIA',
    objective: 'Verificar texto, logo e ícono según su orden configurado y la herencia del diseño normal cuando el seleccionado está vacío.',
    source: 'Guía 3.5 y preguntas frecuentes.',
  },
  {
    id: 15,
    code: 'TC-CHIP-15',
    title: 'Selección en un chip con opciones manuales',
    module: 'Opciones',
    priority: 'ALTA',
    objective: 'Comprobar que la opción elegida sustituya el valor de comparación y controle el filtro.',
    source: 'Guía 4.1 y 4.2.',
  },
  {
    id: 16,
    code: 'TC-CHIP-16',
    title: 'Filtro de obra social y logo en tarjeta',
    module: 'Opciones',
    priority: 'ALTA',
    objective: 'Validar opciones desde el catálogo, filtrado por código de obra social y su representación en tarjeta.',
    source: 'Guía 4.2 y 6.4.',
  },
  {
    id: 17,
    code: 'TC-CHIP-17',
    title: 'Apertura y cierre de la lista de opciones',
    module: 'Opciones',
    priority: 'MEDIA',
    objective: 'Verificar la diferencia entre abrir/cerrar el desplegable y limpiar la opción seleccionada.',
    source: 'Guía 4.1.',
  },
  {
    id: 18,
    code: 'TC-CHIP-18',
    title: 'Correspondencia del bloque con Desktop y Mobile',
    module: 'Integración y dispositivos',
    priority: 'ALTA',
    objective: 'Identificar qué configuración utiliza cada viewport y verificar que la edición llegue al destino previsto.',
    source: 'Captura config-site-editor.png; relación entre instancias pendiente.',
  },
  {
    id: 19,
    code: 'TC-CHIP-19',
    title: 'Uso de la barra en Desktop y Mobile',
    module: 'Integración y dispositivos',
    priority: 'MEDIA',
    objective: 'Validar que la barra y sus controles se puedan utilizar cuando hay más chips de los que caben en pantalla.',
    source: 'UH, experiencia de chips; guía 9, desplazamiento horizontal.',
  },
  {
    id: 20,
    code: 'TC-CHIP-20',
    title: 'Recuperación de chips históricos con lista vacía',
    module: 'Configuración',
    priority: 'MEDIA',
    objective: 'Verificar el comportamiento documentado cuando no existen chips personalizados configurados.',
    source: 'Guía 9, lista de chips completamente vacía.',
  },
  {
    id: 21,
    code: 'TC-CHIP-21',
    title: 'Activación general de la barra de filtros',
    module: 'Configuración',
    priority: 'ALTA',
    objective: 'Comprobar que el interruptor general oculte y restaure la barra sin borrar su configuración.',
    source: 'Guía 3.6.',
  },
  {
    id: 22,
    code: 'TC-CHIP-22',
    title: 'Convivencia entre filtro y orden de sucursales',
    module: 'Integración y dispositivos',
    priority: 'ALTA',
    objective: 'Verificar que filtrar y ordenar permita continuar con una sucursal válida sin incorporar o perder resultados indebidamente.',
    source: 'UH, ordenamiento sin modificar resultados; guía 3.1 y 5.2.',
  },
  {
    id: 23,
    code: 'TC-CHIP-23',
    title: 'Guardado después de una configuración prolongada',
    module: 'Regresión',
    priority: 'ALTA',
    objective: 'Revalidar el bloqueo reportado al guardar después de permanecer configurando el Site Editor.',
    source: 'FARMA-5049, Actividad D5; TQD-1128, Actividad D4.',
  },
  {
    id: 24,
    code: 'TC-CHIP-24',
    title: 'Desactivación y reactivación de un chip',
    module: 'Configuración',
    priority: 'ALTA',
    objective: 'Verificar que el interruptor individual pause un chip sin borrar sus condiciones ni su diseño.',
    source: 'Guía 3.4 y 3.6.',
  },
  {
    id: 25,
    code: 'TC-CHIP-25',
    title: 'Combinación sin resultados y recuperación',
    module: 'Filtrado',
    priority: 'ALTA',
    objective: 'Validar una intersección legítimamente vacía y la posibilidad de recuperar resultados quitando un filtro.',
    source: 'Guía 3.1 y preguntas frecuentes.',
  },
  {
    id: 26,
    code: 'TC-CHIP-26',
    title: 'Uso de un campo extra existente de MasterData',
    module: 'Condiciones y datos',
    priority: 'MEDIA',
    objective: 'Verificar que un atributo adicional existente pueda utilizarse en una condición sin desarrollo.',
    source: 'Guía 6.2 y 8.1.',
  },
  {
    id: 27,
    code: 'TC-CHIP-27',
    title: 'Comparaciones numéricas y valores límite',
    module: 'Condiciones y datos',
    priority: 'ALTA',
    objective: 'Comprobar que es mayor que y es menor que excluyan el valor exactamente igual al umbral.',
    source: 'Guía 6.3, mayor y menor estrictos.',
  },
  {
    id: 28,
    code: 'TC-CHIP-28',
    title: 'Campos vacíos y ausentes en las condiciones',
    module: 'Condiciones y datos',
    priority: 'ALTA',
    objective: 'Verificar tiene dato, no tiene dato y el tratamiento de atributos ausentes en las comparaciones.',
    source: 'Guía 6.3 y 6.4.',
  },
  {
    id: 29,
    code: 'TC-CHIP-29',
    title: 'Colores bordes y sombras del chip',
    module: 'Diseño',
    priority: 'MEDIA',
    objective: 'Validar las propiedades visuales configurables y la dependencia entre color y ancho del borde.',
    source: 'Guía 3.5 y preguntas frecuentes.',
  },
  {
    id: 30,
    code: 'TC-CHIP-30',
    title: 'Eliminación de un chip de prueba',
    module: 'Configuración',
    priority: 'MEDIA',
    objective: 'Comprobar que eliminar una fila quite ese chip y conserve el resto de la lista.',
    source: 'Guía 3.6 y 9.',
  },
];
